# Generated by Django 4.0.2 on 2022-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice1', models.IntegerField()),
                ('Choice2', models.IntegerField()),
                ('Choice3', models.IntegerField()),
                ('Choice4', models.IntegerField()),
                ('Right_Choice', models.IntegerField()),
            ],
        ),
    ]
