# Generated by Django 4.0.2 on 2022-06-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_question', models.IntegerField()),
                ('First_Choice', models.ImageField(upload_to='')),
                ('Second_Choice', models.IntegerField()),
                ('Third_Choice', models.IntegerField()),
                ('Fourth_Choice', models.IntegerField()),
                ('Correct_Choice', models.IntegerField()),
            ],
        ),
    ]
