# Generated by Django 4.0.2 on 2022-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='First_Choice',
            field=models.IntegerField(),
        ),
    ]
