# Generated by Django 4.0.2 on 2022-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Question',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
