# Generated by Django 4.0.2 on 2022-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenttid', models.IntegerField()),
                ('studenttname', models.CharField(max_length=50)),
                ('studenttemail', models.EmailField(max_length=45)),
            ],
        ),
    ]
